import type { Metadata } from "next";
import { Inter, Be_Vietnam_Pro, Dongle } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";


const inter = Inter({ subsets: ["latin"] });
const BeVietnamPro = Be_Vietnam_Pro({
  weight: ['400', '700'], // You can customize the weights as needed
  subsets: ['latin'], // Customize the subset
});

const dongle = Dongle({
  weight: ['400', '700'], // You can customize the weights as needed
  subsets: ['latin'], 
})

export const metadata: Metadata = {
  title: "mida",
  description: "Generated by create next app",
  icons: "",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={BeVietnamPro.className}>{children}</body>
    </html>
  );
}
